default: &default
  adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  adapter: postgresql
  database: rails_test
  username: rails
  password: password
  host: localhost

production:
  <<: *default
  database: db/production.sqlite3