default: &default
  adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  database: <%= ENV["DB_NAME"] || "db/test.sqlite3" %>
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

production:
  <<: *default
  database: db/production.sqlite3