# SQLite. Versions 3.8.0 and up are supported.
# Ensure the SQLite3 gem is defined in your Gemfile
# gem "sqlite3"

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# The database defined as "test" will be erased and re-generated
# from your development database when you run "rake".
test:
  <<: *default
  database: db/test.sqlite3

# Production configuration
production:
  <<: *default
  adapter: sqlite3
  # Update this path to point to your persistent storage
  database: db/production.sqlite3