name: Ruby on Rails CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U rails; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Set up database
        env:
          PGPASSWORD: password
          RAILS_ENV: test
        run: |
          psql -U rails -h localhost -d postgres -c "CREATE DATABASE rails_test;"
          bundle exec rails db:environment:set RAILS_ENV=test
          bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel -A

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman -q -w2

      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update